name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        env:
          _JAVA_OPTIONS: "-Xmx4g"

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Spotless-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Wear APK (if present)
        uses: actions/upload-artifact@v4
        with:
          name: Spotless-wear-debug-apk
          path: wear/build/outputs/apk/debug/wear-debug.apk
          if-no-files-found: ignore
